services:
  autopilot-1:
    build:
      dockerfile: Dockerfile
    container_name: autopilot-1
    restart: unless-stopped
    ports:
      - "9990:9990" # autopilotd service
      - "6080:6080" # noVNC client
      - "6081:6081" # noVNC HTTP proxy
    environment:
      - DISPLAY=:0
    networks:
      - autopilot-network

  autopilot-2:
    build:
      dockerfile: Dockerfile
    container_name: autopilot-2
    restart: unless-stopped
    ports:
      - "9991:9990" # autopilotd service
      - "6082:6080" # noVNC client
      - "6083:6081" # noVNC HTTP proxy
    environment:
      - DISPLAY=:1
    networks:
      - autopilot-network

  autopilot-3:
    build:
      dockerfile: Dockerfile
    container_name: autopilot-3
    restart: unless-stopped
    ports:
      - "9992:9990" # autopilotd service
      - "6084:6080" # noVNC client
      - "6085:6081" # noVNC HTTP proxy
    environment:
      - DISPLAY=:2
    networks:
      - autopilot-network

networks:
  autopilot-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
